#!/usr/bin/env node
/**
 * Regenerate `src/icons.js` — the partner favicons, committed as data URIs.
 *
 *   WIKIMEDIA_UA_CONTACT=you@example.com node tools/build-icons.mjs
 *
 * These used to be fetched at server startup, seventeen hosts deep and serial,
 * BEFORE `server.listen()` — so a scale-to-zero machine spent 6.3–8.4s of every
 * cold start collecting favicons while Fly had booted it in 1.2s and the first
 * visitor waited on the port. They are a fixed list of small, near-static files
 * that change on nobody's schedule but their owners', so the right time to
 * fetch them is once, here, by hand.
 *
 * Run it when the partner manifest (src/partners.js) gains a partner, or when an icon
 * visibly rots. It is not part of the build: a deploy must never depend on
 * seventeen third-party hosts being up.
 *
 * Some hosts refuse Node's fetch stack while serving the identical
 * User-Agent via curl — observed 2026-08-08: `www.artic.edu` 403s and
 * `digitalnz.org` answers a 202 challenge page. For those, fetch the bytes
 * with curl (same UA — the identity is declared either way; it is the HTTP
 * fingerprint they dislike) and prime `.cache/datauri-<sha1(datauri:url)
 * .slice(0,16)>.txt` with the finished data URI before running this. The
 * isImage check below still guards what ships either way.
 */
import { writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

import { coverDataUri } from '../src/http.js'
import { iconUrls } from '../src/emit-html.js'

const OUT = fileURLToPath(new URL('../src/icons.js', import.meta.url))

const entries = []
let missing = 0
for (const url of iconUrls()) {
  // 64 bytes, not the cover default of 1 KB: a favicon is legitimately tiny.
  const uri = await coverDataUri(url, { minBytes: 64 })
  // Size is not enough to know a picture arrived. `openalex.org/favicon.ico`
  // answers **200** with a 2.8 KB HTML error page, which cleared the byte floor
  // and was shipped as OpenAlex's icon — a guaranteed broken image on every
  // page that cited an open paper, for as long as nobody looked. A file that
  // does not say it is an image is not one.
  const isImage = /^data:image\//i.test(uri ?? '')
  if (uri && isImage) entries.push([url, uri])
  else {
    missing++
    const why = uri ? `served ${uri.slice(5, uri.indexOf(';'))}, not an image` : 'no bytes'
    console.error(`  no icon for ${url} — ${why}; it will render as a named entry with no picture`)
  }
  console.error(`${uri && isImage ? 'ok  ' : 'MISS'} ${String(uri?.length ?? 0).padStart(7)}B  ${url}`)
}

const body = `// GENERATED by tools/build-icons.mjs — do not edit by hand.
//
// The partner favicons, inlined once at build time rather than fetched at
// startup. Several of these sites refuse hotlinks outright (CourtListener
// answers 403, GBIF varies by referrer), so a page built on live URLs shows
// broken images for exactly the sources a reader is least likely to recognize
// by name — which is why they travel as bytes at all. Fetching them when the
// server boots was the version that cost every cold visitor 6–8s before the
// port was even open.
//
// Regenerate with: WIKIMEDIA_UA_CONTACT=you@example.com node tools/build-icons.mjs

export const ICONS = new Map([
${entries.map(([u, d]) => `  [${JSON.stringify(u)}, ${JSON.stringify(d)}],`).join('\n')}
])
`

await writeFile(OUT, body)
console.error(
  `\nwrote src/icons.js — ${entries.length} icons, ${(body.length / 1024).toFixed(0)} KB` +
    (missing ? `, ${missing} missing` : ''),
)
