#!/usr/bin/env node
/**
 * Streaming entry point for live discovery — Phase 7 of the design plan, the
 * "actually dynamic" experiment: visit /wiki/<Article Title> and the article
 * spine renders in the time one parse call takes, with the ecosystem's media
 * and sources streaming into the margins as each pivot answers.
 *
 * One chunked HTML response per page; no client framework, no polling. The
 * discovery pipeline, its budgets and its per-host politeness are exactly the
 * batch ones (src/discover.js) — the only difference is when the bytes leave.
 *
 * A page is discovered ONCE. The bytes of a finished stream are stored under
 * this build's id (src/page-cache.js) and replayed to everyone who asks next,
 * so a repeat view is a file read rather than a rerun of the pipeline over a
 * request cache that never expires anyway.
 *
 *   WIKIMEDIA_UA_CONTACT=you@example.com node serve.js [port]
 */
import { createServer } from 'node:http'

import { admits, isShowcase } from './src/admission.js'
import { discover } from './src/discover.js'
import { busyPage, frontPage } from './src/front-page.js'
import {
  CACHE,
  coverDataUri,
  fromDataUri,
  hotlinkUnsafe,
  imgKey,
  readFacts,
  writeFacts,
} from './src/http.js'
import { buildId, purgeStalePages, readPage, writePage } from './src/page-cache.js'
import { startSweeping } from './src/sweep.js'
import { userAgent } from './src/wmf.js'
import {
  streamBand,
  streamClose,
  streamHeroExtras,
  streamOpen,
} from './src/emit-html.js'
import { ICONS } from './src/icons.js'
import { escapeHtml } from './src/html.js'

// Fail at startup, not mid-stream, if the operator contact is unset.
userAgent('tapestry-gen')

const PORT = Number(process.argv[2] ?? process.env.PORT ?? 8787)

// ---- Images: proxied by this server, not inlined into the HTML -------------
//
// The batch renderer (spike.js) inlines these as data: URIs because its output
// has to be one self-contained, byte-reproducible file. A streamed page has the
// opposite needs, and inlining cost it three ways: the bytes sat on each band's
// critical path (the fragment could not be written until every cover had been
// fetched, serially, through the per-host queue), base64 was a third of the
// page — 164 KB of Angkor Wat's 494 KB — and because the same fifteen icons
// were re-embedded in full in every page, a reader's browser could never cache
// one across two articles.
//
// Serving them from a path fixes all three at once: the fragment goes out
// immediately, the browser fetches images in parallel on its own connections,
// and it caches them between pages. The FETCH is still server-side under our
// User-Agent, which is what the OSMF tile policy and the OpenLibrary redirect
// argument actually require — neither ever asked for the bytes to be in the
// HTML.
//
// Keyed by a hash of the URL, and only URLs this server has itself decided to
// serve are in the registry: an image proxy that will fetch whatever a caller
// names is an open proxy, and this one cannot be asked for a URL it did not
// choose.
//
// The registry is written through to disk as well as held in memory, because
// stored pages outlive the process that rendered them (src/page-cache.js): a
// replayed page names `/img/` paths this process never minted, and without the
// disk half every image on it would 404 after a restart. It stays closed
// against the open-proxy problem for the same reason it always was — an entry
// exists only where `imgPath` put it, so the set of URLs this server will fetch
// is still exactly the set it chose itself, and the key is verified against the
// URL on the way back out.
const proxied = new Map()
function imgPath(url) {
  const key = imgKey(url)
  if (!proxied.has(key)) {
    proxied.set(key, url)
    // Fire and forget: a failed write costs this image a thumbnail on a
    // replayed page after a restart, and the card's onerror already handles a
    // missing image. writeFacts says so itself when it fails, and does not
    // reject — the catch here is because an unawaited promise is the one place
    // where "does not reject" being wrong would end the process, and this is a
    // path that runs while a reader is waiting on bytes.
    writeFacts('img', [[key, url]]).catch(() => {})
  }
  return `/img/${key}`
}

/** The URL behind an `/img/` key: this process's memory, then the volume. */
async function proxiedUrl(key) {
  if (proxied.has(key)) return proxied.get(key)
  const url = (await readFacts('img', [key])).get(key)
  // The path IS the hash of the URL, so a remembered entry can be checked
  // rather than trusted: anything that does not hash back to its own key was
  // not written by imgPath, and this server does not fetch it.
  if (typeof url !== 'string' || imgKey(url) !== key) return null
  proxied.set(key, url)
  return url
}

// Source icons are page furniture, not findings, and arrive as committed bytes
// (src/icons.js, regenerated by tools/build-icons.mjs). They used to be FETCHED
// here at startup — fifteen hosts, serial, before `listen()` — which on a
// scale-to-zero machine cost 6.3–8.4s of every cold start while Fly had booted
// the VM in 1.2s and the first visitor sat waiting on a port that was not open
// yet. Nothing this server does before binding may touch the network.
//
// Being a fixed list, their paths also exist before the first request arrives.
const icons = new Map([...ICONS.keys()].map((url) => [url, imgPath(url)]))

/** Where one band's images will be served from. No network: it only names them. */
function bandInline(b) {
  const inline = new Map(icons)
  for (const e of b.entries ?? []) {
    // Which images must not be hotlinked — the shared predicate in src/http.js
    // says why each class is here. Everything else is a partner's own
    // thumbnail URL and is linked directly, as before.
    if (!hotlinkUnsafe(e)) continue
    if (inline.has(e.imageUrl)) continue
    inline.set(e.imageUrl, imgPath(e.imageUrl))
  }
  return inline
}

// The front page: rendered once at startup, pointing at the same served source
// icons the article pages use — so a visitor who arrives here and then opens an
// article has already cached every one of them.
const INDEX = frontPage({ inline: icons })

// The busy page, built once for the same reason the front page is — and here
// the reason is sharper: the moment it is needed is the moment this server has
// no capacity to spare. It offers the showcase, which the reserve below is what
// makes true.
const BUSY = busyPage()

// Each discovery fans out dozens of upstream requests (politely — the
// per-host queues serialize them globally), so inbound load must be capped
// where it arrives: a few pages at a time is a demo, an unbounded queue of
// them is someone else's traffic problem.
const MAX_CONCURRENT = Number(process.env.MAX_CONCURRENT ?? 4)
// Slots general traffic cannot take, kept for the six pages the front page
// promises are ready. Since the page cache landed this covers a much smaller
// job than it did: a stored render needs no slot at all, so the reserve now
// only matters in the windows where the showcase is genuinely cold — a fresh
// volume, the minutes after a deploy while `warm.js` refills, an eviction
// sweep. It survives because the busy page's offer has to stay true in those
// windows too. The argument, and why it widens nothing anyone else sees, is in
// src/admission.js.
const SHOWCASE_RESERVE = Number(process.env.SHOWCASE_RESERVE ?? 2)
let inFlight = 0

// Which rendering this process does. Stored pages are keyed by it, so a deploy
// retires every one of them rather than serving last build's markup forever.
const BUILD = buildId()

/**
 * The day a render was discovered, for the line at the foot of the page.
 *
 * A stored page carries the date it was made, which is the disclosure this
 * site owed its readers before the page cache existed and did not make: the
 * request cache has never expired, so a "warm" page has always been showing
 * the ecosystem as it stood when someone first asked for it. Now the page
 * says so. UTC and long-form American English, per the subtree's invariant.
 */
const discoveredOn = () =>
  new Intl.DateTimeFormat('en-US', {
    timeZone: 'UTC', year: 'numeric', month: 'long', day: 'numeric',
  }).format(new Date())

const server = createServer(async (req, res) => {
  const url = new URL(req.url, 'http://localhost')
  if (url.pathname === '/' || url.pathname === '/index.html') {
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' })
    res.end(INDEX)
    return
  }
  const img = /^\/img\/([0-9a-f]{16})$/.exec(url.pathname)
  if (img) {
    const target = await proxiedUrl(img[1])
    // A key nothing ever minted — or one whose registry entry has been swept.
    // The image is missing; the page is not broken.
    if (!target) {
      res.writeHead(404, { 'Content-Type': 'text/plain' })
      res.end('unknown image\n')
      return
    }
    try {
      // Icons are already bytes; everything else rides the same disk cache and
      // per-host queue as the rest of this project's traffic.
      const uri = ICONS.get(target) ?? (await coverDataUri(target))
      const decoded = uri && fromDataUri(uri)
      if (!decoded) {
        // OpenLibrary answers a coverless ISBN with a placeholder, which
        // `coverDataUri` reports as nothing. A 404 lets the card drop its
        // thumbnail, which is what a broken image would have to do anyway.
        res.writeHead(404, { 'Content-Type': 'text/plain' })
        res.end('no image\n')
        return
      }
      res.writeHead(200, {
        'Content-Type': decoded.type,
        'Content-Length': decoded.body.length,
        // The path is a hash of the URL, and these files do not change under
        // theirs. A week is long enough to cache across a reading session and
        // short enough that a replaced cover is not permanent.
        'Cache-Control': 'public, max-age=604800',
      })
      res.end(decoded.body)
    } catch (e) {
      console.error(`  image ${target}: ${e.message}`)
      res.writeHead(502, { 'Content-Type': 'text/plain' })
      res.end('upstream image failed\n')
    }
    return
  }
  if (url.pathname === '/robots.txt') {
    // Every /wiki/ visit spends upstream API capacity; crawlers must not.
    // Staging (ROBOTS_DISALLOW_ALL) refuses crawlers entirely: it exists for
    // one reviewer, and an indexed staging page is a wrong answer forever.
    res.writeHead(200, { 'Content-Type': 'text/plain' })
    res.end(
      process.env.ROBOTS_DISALLOW_ALL
        ? 'User-agent: *\nDisallow: /\n'
        : 'User-agent: *\nDisallow: /wiki/\n',
    )
    return
  }
  const m = /^\/wiki\/(.+)$/.exec(url.pathname)
  if (!m) {
    res.writeHead(404, { 'Content-Type': 'text/plain' })
    res.end('not found\n')
    return
  }
  const started = Date.now()
  // Decoded before the gate, because both what may be replayed and which lane
  // this request may use depend on which article it asks for. A malformed
  // escape throws here rather than inside the handler's try, so it answers for
  // itself: it is a bad request, and it must not take a slot on the way out.
  let page
  try {
    page = decodeURIComponent(m[1]).replace(/_/g, ' ')
  } catch {
    res.writeHead(400, { 'Content-Type': 'text/plain' })
    res.end('bad title encoding\n')
    return
  }
  // A page this build has already rendered is replayed whole, before the gate
  // and without taking a slot — it is a file read, not a discovery, and the cap
  // exists to bound discoveries. This is also the answer to a question the
  // server could not previously ask: whether a page is warm was a property of a
  // few hundred cache files and unknowable before running it; now it is one
  // lookup.
  const stored = await readPage(CACHE, BUILD, page)
  if (stored) {
    res.writeHead(200, {
      'Content-Type': 'text/html; charset=utf-8',
      'Content-Length': Buffer.byteLength(stored),
      // Still no-store, deliberately: the volume is the cache now, and letting
      // browsers hold their own copies is a separate decision with its own
      // invalidation problem (a build id they never see).
      'Cache-Control': 'no-store',
    })
    res.end(stored)
    console.error(`${page}: replayed in ${Date.now() - started}ms`)
    return
  }
  if (!admits({
    inFlight,
    showcase: isShowcase(page),
    max: MAX_CONCURRENT,
    reserve: SHOWCASE_RESERVE,
  })) {
    res.writeHead(503, { 'Content-Type': 'text/html; charset=utf-8', 'Retry-After': '15' })
    res.end(BUSY)
    return
  }
  inFlight++
  let streaming = false
  // Every byte this response sends, kept so the finished page can be stored and
  // replayed. The bytes SENT are the artifact — bands stream in completion
  // order, so a later re-render is not obliged to reproduce them, and the
  // concatenation is the same standalone document `warm.js` reads today.
  const sent = []
  const write = (chunk) => {
    sent.push(chunk)
    res.write(chunk)
  }
  // The article discovery actually read, once redirects resolve — set from the
  // spine event, which fires before any header goes out. `page` stays the
  // reader's request; `title` is what the page may truthfully call itself.
  let title = page
  try {
    const { bands, stats, reach } = await discover(page, {
      async emit(type, data) {
        if (type === 'spine') {
          title = data.page
          res.writeHead(200, {
            'Content-Type': 'text/html; charset=utf-8',
            // The volume holds the copy, not the reader's browser: this render
            // is about to be stored under this build's id, where it can be
            // retired by a deploy. A browser copy could not be.
            'Cache-Control': 'no-store',
          })
          write(
            streamOpen({
              title,
              units: data.units,
              inline: icons,
              home: process.env.SITE_HOME ?? '/',
            }),
          )
          streaming = true
        }
        if (type === 'band') {
          // Build the fragment fully before the single write, so concurrent
          // band tasks never interleave bytes. Nothing here awaits the network
          // any more — images are named, not fetched (see imgPath above).
          const fragment = streamBand(data, bandInline(data))
          if (fragment) write(fragment)
        }
      },
    })
    const inline = new Map(icons)
    for (const b of bands) for (const [k, v] of bandInline(b)) inline.set(k, v)
    // The front page IS the home now; the hero's main-page link points there.
    write(streamHeroExtras(bands, { inline, reach, home: process.env.SITE_HOME ?? '/' }))
    write(
      streamClose({
        // Dated, because this page is about to become the answer to every later
        // request for it. The date was owed before the page cache existed —
        // nothing in `.cache/` expires, so a repeat view has always been the
        // ecosystem as it stood when someone first asked — and "streamed as it
        // was found" quietly implied otherwise.
        provenance:
          `Discovered live from the English Wikipedia article ` +
          `<a href="https://en.wikipedia.org/wiki/${encodeURIComponent(title.replace(/ /g, '_'))}">` +
          `${escapeHtml(title)}</a> on ${discoveredOn()} — no curated dataset. ` +
          `Later visits are served this same render, so what you see is the open ` +
          `ecosystem as it was that day.`,
      }),
    )
    res.end()
    console.error(
      `${title}: ${stats.sections} sections in ${((Date.now() - started) / 1000).toFixed(1)}s`,
    )
    // Stored only here, on the path where discovery actually finished: a page
    // cut short by an upstream failure is a page that must be discovered again,
    // not one to serve to everybody who asks next. Keyed by the title the
    // reader asked for; a redirect earns its own entry under its own name.
    await writePage(CACHE, BUILD, page, sent.join(''))
  } catch (e) {
    console.error(`${page}: ${e.message}`)
    if (!streaming) {
      const missing = /missingtitle|invalidtitle/.test(e.message)
      res.writeHead(missing ? 404 : 500, { 'Content-Type': 'text/html; charset=utf-8' })
      res.end(
        `<!doctype html><meta charset="utf-8"><p style="font-family:system-ui;margin:15vh auto;max-width:40rem">` +
          (missing
            ? `No English Wikipedia article called “${escapeHtml(page)}”.`
            : `Discovery failed: ${escapeHtml(e.message)}`) +
          ` <a href="/">Try another</a>.</p>\n`,
      )
    } else {
      // The spine is already on the wire; say what happened where the reader is.
      res.write(
        `<p class="disclosure">Discovery stopped early: ${escapeHtml(e.message)}</p>` +
          streamClose({}),
      )
      res.end()
    }
  } finally {
    inFlight--
  }
})

server.listen(PORT, '0.0.0.0', () => {
  console.error(`live discovery on http://localhost:${PORT}/ (build ${BUILD}) — try /wiki/Ludwig_Prandtl`)
  // Renders from a build this process is not serving can never be served
  // again; dropping them here rather than leaving them to the LRU sweep keeps
  // a deploy's worth of dead pages off the volume. After listen(), like the
  // sweep: a visitor must never wait on housekeeping.
  purgeStalePages(CACHE, BUILD)
  // Only after the port is open: the cache lives on a durable volume now, so
  // it grows without bound (~4 MB a page) and needs a ceiling — but a visitor
  // must never wait on housekeeping. Default 2 GB against a 3 GB volume.
  startSweeping(CACHE, { capBytes: Number(process.env.CACHE_MAX_MB ?? 2048) * 1024 * 1024 })
})

// A deploy or scale-down stops this machine with a signal. A streamed page
// cut mid-response looks like a broken render to the person watching it, so
// drain instead: refuse new connections, let in-flight discoveries finish,
// and only then exit. fly.toml's kill_timeout is set above this bound.
let draining = false
for (const sig of ['SIGINT', 'SIGTERM']) {
  process.on(sig, () => {
    if (draining) process.exit(1)
    draining = true
    console.error(`${sig}: draining ${inFlight} in-flight ${inFlight === 1 ? 'discovery' : 'discoveries'}`)
    server.close(() => process.exit(0))
    server.closeIdleConnections()
    setTimeout(() => process.exit(0), 40_000).unref()
  })
}
