#!/usr/bin/env node
/**
 * Streaming entry point for live discovery — Phase 7 of the design plan, the
 * "actually dynamic" experiment: visit /wiki/<Article Title> and the article
 * spine renders in the time one parse call takes, with the ecosystem's media
 * and sources streaming into the margins as each pivot answers.
 *
 * One chunked HTML response per page; no client framework, no polling. The
 * discovery pipeline, its budgets and its per-host politeness are exactly the
 * batch ones (src/discover.js) — the only difference is when the bytes leave.
 * Repeat views ride the same disk cache as spike.js, so a page you have seen
 * before arrives essentially at once.
 *
 *   WIKIMEDIA_UA_CONTACT=you@example.com node serve.js [port]
 */
import { createServer } from 'node:http'
import { createHash } from 'node:crypto'

import { admits, isShowcase } from './src/admission.js'
import { discover } from './src/discover.js'
import { busyPage, frontPage } from './src/front-page.js'
import { CACHE, coverDataUri, fromDataUri, hotlinkUnsafe } from './src/http.js'
import { startSweeping } from './src/sweep.js'
import { userAgent } from './src/wmf.js'
import {
  streamBand,
  streamClose,
  streamHeroExtras,
  streamOpen,
} from './src/emit-html.js'
import { ICONS } from './src/icons.js'
import { escapeHtml } from './src/html.js'

// Fail at startup, not mid-stream, if the operator contact is unset.
userAgent('tapestry-gen')

const PORT = Number(process.argv[2] ?? process.env.PORT ?? 8787)

// ---- Images: proxied by this server, not inlined into the HTML -------------
//
// The batch renderer (spike.js) inlines these as data: URIs because its output
// has to be one self-contained, byte-reproducible file. A streamed page has the
// opposite needs, and inlining cost it three ways: the bytes sat on each band's
// critical path (the fragment could not be written until every cover had been
// fetched, serially, through the per-host queue), base64 was a third of the
// page — 164 KB of Angkor Wat's 494 KB — and because the same fifteen icons
// were re-embedded in full in every page, a reader's browser could never cache
// one across two articles.
//
// Serving them from a path fixes all three at once: the fragment goes out
// immediately, the browser fetches images in parallel on its own connections,
// and it caches them between pages. The FETCH is still server-side under our
// User-Agent, which is what the OSMF tile policy and the OpenLibrary redirect
// argument actually require — neither ever asked for the bytes to be in the
// HTML.
//
// Keyed by a hash of the URL, and only URLs this server has itself decided to
// serve are in the registry: an image proxy that will fetch whatever a caller
// names is an open proxy, and this one cannot be asked for a URL it did not
// choose.
const proxied = new Map()
function imgPath(url) {
  const key = createHash('sha1').update(url).digest('hex').slice(0, 16)
  proxied.set(key, url)
  return `/img/${key}`
}

// Source icons are page furniture, not findings, and arrive as committed bytes
// (src/icons.js, regenerated by tools/build-icons.mjs). They used to be FETCHED
// here at startup — fifteen hosts, serial, before `listen()` — which on a
// scale-to-zero machine cost 6.3–8.4s of every cold start while Fly had booted
// the VM in 1.2s and the first visitor sat waiting on a port that was not open
// yet. Nothing this server does before binding may touch the network.
//
// Being a fixed list, their paths also exist before the first request arrives.
const icons = new Map([...ICONS.keys()].map((url) => [url, imgPath(url)]))

/** Where one band's images will be served from. No network: it only names them. */
function bandInline(b) {
  const inline = new Map(icons)
  for (const e of b.entries ?? []) {
    // Which images must not be hotlinked — the shared predicate in src/http.js
    // says why each class is here. Everything else is a partner's own
    // thumbnail URL and is linked directly, as before.
    if (!hotlinkUnsafe(e)) continue
    if (inline.has(e.imageUrl)) continue
    inline.set(e.imageUrl, imgPath(e.imageUrl))
  }
  return inline
}

// The front page: rendered once at startup, pointing at the same served source
// icons the article pages use — so a visitor who arrives here and then opens an
// article has already cached every one of them.
const INDEX = frontPage({ inline: icons })

// The busy page, built once for the same reason the front page is — and here
// the reason is sharper: the moment it is needed is the moment this server has
// no capacity to spare. It offers the showcase, which the reserve below is what
// makes true.
const BUSY = busyPage()

// Each discovery fans out dozens of upstream requests (politely — the
// per-host queues serialize them globally), so inbound load must be capped
// where it arrives: a few pages at a time is a demo, an unbounded queue of
// them is someone else's traffic problem.
const MAX_CONCURRENT = Number(process.env.MAX_CONCURRENT ?? 4)
// Slots general traffic cannot take, kept for the six pages the front page
// promises are ready — a warm one of those makes no upstream request at all,
// which is the thing the cap exists to bound. The argument, and why this does
// not widen anything anyone else sees, is in src/admission.js.
const SHOWCASE_RESERVE = Number(process.env.SHOWCASE_RESERVE ?? 2)
let inFlight = 0

const server = createServer(async (req, res) => {
  const url = new URL(req.url, 'http://localhost')
  if (url.pathname === '/' || url.pathname === '/index.html') {
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' })
    res.end(INDEX)
    return
  }
  const img = /^\/img\/([0-9a-f]{16})$/.exec(url.pathname)
  if (img) {
    const target = proxied.get(img[1])
    // A key this process never minted — a page cached in someone's browser
    // from before a restart. The image is missing; the page is not broken.
    if (!target) {
      res.writeHead(404, { 'Content-Type': 'text/plain' })
      res.end('unknown image\n')
      return
    }
    try {
      // Icons are already bytes; everything else rides the same disk cache and
      // per-host queue as the rest of this project's traffic.
      const uri = ICONS.get(target) ?? (await coverDataUri(target))
      const decoded = uri && fromDataUri(uri)
      if (!decoded) {
        // OpenLibrary answers a coverless ISBN with a placeholder, which
        // `coverDataUri` reports as nothing. A 404 lets the card drop its
        // thumbnail, which is what a broken image would have to do anyway.
        res.writeHead(404, { 'Content-Type': 'text/plain' })
        res.end('no image\n')
        return
      }
      res.writeHead(200, {
        'Content-Type': decoded.type,
        'Content-Length': decoded.body.length,
        // The path is a hash of the URL, and these files do not change under
        // theirs. A week is long enough to cache across a reading session and
        // short enough that a replaced cover is not permanent.
        'Cache-Control': 'public, max-age=604800',
      })
      res.end(decoded.body)
    } catch (e) {
      console.error(`  image ${target}: ${e.message}`)
      res.writeHead(502, { 'Content-Type': 'text/plain' })
      res.end('upstream image failed\n')
    }
    return
  }
  if (url.pathname === '/robots.txt') {
    // Every /wiki/ visit spends upstream API capacity; crawlers must not.
    // Staging (ROBOTS_DISALLOW_ALL) refuses crawlers entirely: it exists for
    // one reviewer, and an indexed staging page is a wrong answer forever.
    res.writeHead(200, { 'Content-Type': 'text/plain' })
    res.end(
      process.env.ROBOTS_DISALLOW_ALL
        ? 'User-agent: *\nDisallow: /\n'
        : 'User-agent: *\nDisallow: /wiki/\n',
    )
    return
  }
  const m = /^\/wiki\/(.+)$/.exec(url.pathname)
  if (!m) {
    res.writeHead(404, { 'Content-Type': 'text/plain' })
    res.end('not found\n')
    return
  }
  // Decoded before the gate, because which lane this request may use depends on
  // which article it asks for. A malformed escape throws here rather than
  // inside the handler's try, so it answers for itself: it is a bad request,
  // and it must not take a slot on the way out.
  let page
  try {
    page = decodeURIComponent(m[1]).replace(/_/g, ' ')
  } catch {
    res.writeHead(400, { 'Content-Type': 'text/plain' })
    res.end('bad title encoding\n')
    return
  }
  if (!admits({
    inFlight,
    showcase: isShowcase(page),
    max: MAX_CONCURRENT,
    reserve: SHOWCASE_RESERVE,
  })) {
    res.writeHead(503, { 'Content-Type': 'text/html; charset=utf-8', 'Retry-After': '15' })
    res.end(BUSY)
    return
  }
  inFlight++
  const started = Date.now()
  let streaming = false
  // The article discovery actually read, once redirects resolve — set from the
  // spine event, which fires before any header goes out. `page` stays the
  // reader's request; `title` is what the page may truthfully call itself.
  let title = page
  try {
    const { bands, stats, reach } = await discover(page, {
      async emit(type, data) {
        if (type === 'spine') {
          title = data.page
          res.writeHead(200, {
            'Content-Type': 'text/html; charset=utf-8',
            // Every view re-runs discovery (the disk cache is the cache);
            // a stale copy of a streaming page is worth less than a fresh run.
            'Cache-Control': 'no-store',
          })
          res.write(
            streamOpen({
              title,
              units: data.units,
              inline: icons,
              home: process.env.SITE_HOME ?? '/',
            }),
          )
          streaming = true
        }
        if (type === 'band') {
          // Build the fragment fully before the single write, so concurrent
          // band tasks never interleave bytes. Nothing here awaits the network
          // any more — images are named, not fetched (see imgPath above).
          const fragment = streamBand(data, bandInline(data))
          if (fragment) res.write(fragment)
        }
      },
    })
    const inline = new Map(icons)
    for (const b of bands) for (const [k, v] of bandInline(b)) inline.set(k, v)
    // The front page IS the home now; the hero's main-page link points there.
    res.write(streamHeroExtras(bands, { inline, reach, home: process.env.SITE_HOME ?? '/' }))
    res.write(
      streamClose({
        provenance:
          `Discovered live from the English Wikipedia article ` +
          `<a href="https://en.wikipedia.org/wiki/${encodeURIComponent(title.replace(/ /g, '_'))}">` +
          `${escapeHtml(title)}</a> — no curated dataset, streamed as it was found.`,
      }),
    )
    res.end()
    console.error(
      `${title}: ${stats.sections} sections in ${((Date.now() - started) / 1000).toFixed(1)}s`,
    )
  } catch (e) {
    console.error(`${page}: ${e.message}`)
    if (!streaming) {
      const missing = /missingtitle|invalidtitle/.test(e.message)
      res.writeHead(missing ? 404 : 500, { 'Content-Type': 'text/html; charset=utf-8' })
      res.end(
        `<!doctype html><meta charset="utf-8"><p style="font-family:system-ui;margin:15vh auto;max-width:40rem">` +
          (missing
            ? `No English Wikipedia article called “${escapeHtml(page)}”.`
            : `Discovery failed: ${escapeHtml(e.message)}`) +
          ` <a href="/">Try another</a>.</p>\n`,
      )
    } else {
      // The spine is already on the wire; say what happened where the reader is.
      res.write(
        `<p class="disclosure">Discovery stopped early: ${escapeHtml(e.message)}</p>` +
          streamClose({}),
      )
      res.end()
    }
  } finally {
    inFlight--
  }
})

server.listen(PORT, '0.0.0.0', () => {
  console.error(`live discovery on http://localhost:${PORT}/ — try /wiki/Ludwig_Prandtl`)
  // Only after the port is open: the cache lives on a durable volume now, so
  // it grows without bound (~4 MB a page) and needs a ceiling — but a visitor
  // must never wait on housekeeping. Default 2 GB against a 3 GB volume.
  startSweeping(CACHE, { capBytes: Number(process.env.CACHE_MAX_MB ?? 2048) * 1024 * 1024 })
})

// A deploy or scale-down stops this machine with a signal. A streamed page
// cut mid-response looks like a broken render to the person watching it, so
// drain instead: refuse new connections, let in-flight discoveries finish,
// and only then exit. fly.toml's kill_timeout is set above this bound.
let draining = false
for (const sig of ['SIGINT', 'SIGTERM']) {
  process.on(sig, () => {
    if (draining) process.exit(1)
    draining = true
    console.error(`${sig}: draining ${inFlight} in-flight ${inFlight === 1 ? 'discovery' : 'discoveries'}`)
    server.close(() => process.exit(0))
    server.closeIdleConnections()
    setTimeout(() => process.exit(0), 40_000).unref()
  })
}
